export const TAG_CATEGORY = {
    GENERAL: 0,
    ARTIST: 1,
    COPYRIGHT: 3,
    CHARACTER: 4,
    META: 5,
};

export const DANBOORU_TAG_CSV_PATH = "/danbooru_tags_post_count.csv";

// --------------- Scoring thresholds ------------------------------------------

/** Tags scoring below this are discarded entirely. */
export const SCORE_DISCARD = 35;

/** Tags scoring below this are placed in the low-confidence "Unknown" bucket. */
export const SCORE_LOW_CONFIDENCE = 55;

/** Perfect match: tag name exactly equals the normalized query. */
export const SCORE_EXACT = 100;

/** Prefix match: tag name starts with the normalized query. */
export const SCORE_PREFIX = 80;

/** Contains match: tag name contains the normalized query. */
export const SCORE_CONTAINS = 60;

/** Maximum overlap-based score for partial token matches. */
export const SCORE_OVERLAP_MAX = 50;

// --------------- Source Material / Franchise mapping --------------------------
//
// Maps copyright tag name (underscore form) → human-readable franchise label.
// Used by TextFormatter.jsx to derive the "Source Material" group from
// copyright-category tags. Populate this as you discover new series.

export const FRANCHISE_LABELS = {
    genshin_impact: "Genshin Impact",
    honkai_star_rail: "Honkai: Star Rail",
    honkai_impact_3rd: "Honkai Impact 3rd",
    zenless_zone_zero: "Zenless Zone Zero",
    hololive: "Hololive",
    arknights: "Arknights",
    azur_lane: "Azur Lane",
    fate_grand_order: "Fate/Grand Order",
    fate_stay_night: "Fate/Stay Night",
    blue_archive: "Blue Archive",
    touhou: "Touhou Project",
    nikke: "Goddess of Victory: Nikke",
    nikke_goddess_of_victory: "Goddess of Victory: Nikke",
    project_sekai: "Project Sekai",
    hatsune_miku: "Vocaloid",
    vocaloid: "Vocaloid",
    pokemon: "Pokémon",
    final_fantasy: "Final Fantasy",
    fire_emblem: "Fire Emblem",
    persona_5: "Persona 5",
    persona_3: "Persona 3",
    persona_4: "Persona 4",
    cyberpunk_edgerunners: "Cyberpunk: Edgerunners",
    cyberpunk_2077: "Cyberpunk 2077",
    league_of_legends: "League of Legends",
    valorant: "Valorant",
    overwatch: "Overwatch",
    guilty_gear: "Guilty Gear",
    street_fighter: "Street Fighter",
    tekken: "Tekken",
    elden_ring: "Elden Ring",
    dark_souls: "Dark Souls",
    nier_automata: "NieR: Automata",
    nier: "NieR",
    danganronpa: "Danganronpa",
    love_live: "Love Live!",
    idolmaster: "THE iDOLM@STER",
    kancolle: "Kantai Collection",
    girls_frontline: "Girls' Frontline",
    tower_of_fantasy: "Tower of Fantasy",
    wuthering_waves: "Wuthering Waves",
    punishing_gray_raven: "Punishing: Gray Raven",
    star_rail: "Honkai: Star Rail",
    hololive_english: "Hololive English",
    hololive_indonesia: "Hololive Indonesia",
    nijisanji: "Nijisanji",
    vshojo: "VShojo",
    vtuber: "VTuber",
    doki_doki_literature_club: "Doki Doki Literature Club",
    omori: "OMORI",
    undertale: "Undertale",
    deltarune: "Deltarune",
};

/** Derive a franchise label from a copyright tag name (underscore form). */
export function getFranchiseLabel(tagName) {
    const key = tagName.toLowerCase().replace(/\s+/g, "_");
    return FRANCHISE_LABELS[key] || null;
}

// --------------- Style / Quality keywords ------------------------------------

export const STYLE_KEYWORDS = [
    "masterpiece", "best quality", "high quality", "8k", "4k", "cinematic", "photorealistic",
    "anime coloring", "dramatic lighting", "volumetric lighting", "depth of field", "lineart",
    "shaded", "cel shading", "render", "illustration", "ultra detailed", "detailed",
    "score_", "quality", "stylized", "painting", "watercolor", "sketch", "concept art",
    "anime screenshot", "pixelated", "pixel art", "realistic", "amazing", "amazing quality",
    "cyberpunk", "steampunk", "synthwave", "vaporwave", "surreal", "abstract", "impressionism", "cubism",
    "art deco", "art nouveau", "glitch art", "glitch", "low poly", "retro",
    "bloom", "bokeh", "lens flare", "motion blur", "silhouette", "chiaroscuro", "chromatic aberration",
    "film grain", "gradient", "halftone", "scanlines", "dithering", "posterize",
    "monochrome", "greyscale", "sepia", "pastel colors", "pastel", "saturated", "saturated colors",
    "muted color", "dark", "moody", "vibrant", "colorful", "limited palette", "neon palette",
    "3d", "comic", "manga", "official art", "scan", "promo", "promo art", "advertisement",
    "flat color", "vector", "vector art", "oil painting", "watercolor painting", "digital painting",
    "traditional media", "hand drawn", "sketch style", "comic book style", "comic style",
];

// --------------- Landscape / Scene keywords ----------------------------------

export const LANDSCAPE_KEYWORDS = [
    "sky", "cloud", "clouds", "sunset", "sunrise", "dusk", "dawn", "twilight", "night",
    "day", "daytime", "morning", "afternoon", "evening", "midnight", "noon",
    "forest", "woods", "woodland", "jungle", "rainforest",
    "meadow", "field", "grassland", "prairie", "savanna", "steppe",
    "mountain", "mountains", "mountain range", "hill", "hills", "rolling hills", "mountain peak",
    "valley", "canyon", "gorge", "ravine", "crevasse", "chasm",
    "river", "stream", "creek", "brook", "waterfall", "rapids",
    "lake", "pond", "lagoon", "marsh", "swamp", "wetland", "bog",
    "ocean", "sea", "beach", "shore", "coastline", "reef",
    "island", "archipelago", "atoll", "peninsula",
    "desert", "dunes", "sand dunes", "oasis",
    "volcano", "volcanic", "lava", "hot spring", "geyser",
    "cave", "cavern", "grotto", "underground",
    "cliff", "cliff face", "rock face", "escarpment", "overhang", "natural arch",
    "ice", "glacier", "iceberg", "frozen", "snowy", "snow", "snowfield",
    "rain", "raining", "stormy", "storm", "thunderstorm", "lightning", "thunder",
    "wind", "windy", "blizzard", "hail", "frost", "dew", "mist", "fog", "foggy",
    "space", "outer space", "starry sky", "stars", "moon", "full moon", "crescent moon",
    "planet", "planets", "satellite", "orbit", "cosmic", "galactic", "nebula",
    "alien planet", "alien landscape", "mars", "lunar surface",
    "city", "town", "village", "metropolis", "cityscape", "urban",
    "street", "street scene", "alley", "alleyway", "lane", "pathway", "path", "road", "highway",
    "intersection", "crossing", "traffic", "traffic light",
    "sidewalk", "pavement", "asphalt", "concrete", "cobblestone",
    "building", "office", "skyscraper", "architecture",
    "house", "residential", "neighborhood", "suburb", "suburban",
    "apartment", "apartment building", "condo", "mansion", "estate",
    "cabin", "cottage", "hut", "pagoda", "pavilion", "gazebo",
    "church", "cathedral", "temple", "shrine", "mosque", "synagogue", "monastery",
    "castle", "palace", "fortress", "fort", "keep", "tower", "watchtower",
    "ruins", "ruins of", "ruin", "ancient ruins",
    "wall", "stone wall", "brick wall", "defensive wall", "city wall",
    "gate", "city gate", "archway", "tunnel", "underpass",
    "bridge", "arched bridge", "stone bridge", "wooden bridge", "suspension bridge",
    "doorway", "portal", "threshold",
    "plaza", "square", "courtyard", "marketplace", "market", "bazaar",
    "shop", "store", "storefront",
    "restaurant", "cafe", "cafeteria", "bar", "pub", "tavern", "inn", "hotel",
    "hospital", "clinic", "pharmacy", "laboratory", "lab",
    "factory", "warehouse", "industrial",
    "school", "schoolhouse", "academy", "college", "university", "campus", "classroom",
    "library", "museum", "gallery", "theater", "cinema", "auditorium",
    "park", "public park", "urban park", "national park",
    "garden", "garden path", "botanical garden", "zen garden", "japanese garden", "flower garden",
    "playground", "stadium", "arena", "coliseum", "amphitheater",
    "gymnasium", "gym", "pool", "swimming pool", "fountain",
    "monument", "memorial", "statue", "sculpture", "obelisk", "column",
    "dock", "harbor", "port", "seaport", "marina", "pier", "wharf",
    "airport", "airfield", "runway", "hangar",
    "train station", "train platform", "railway", "railroad", "train track",
    "bus station", "bus terminal", "bus stop", "subway station",
    "parking", "parking lot", "parking garage",
    "gas station", "lighthouse", "power plant", "wind turbine", "antenna", "radio tower",
    "room", "interior", "indoors", "inside",
    "bedroom", "bathroom", "shower", "bathtub", "sink", "toilet", "mirror",
    "living room", "lounge", "dining room", "kitchen", "office", "home office", "desk",
    "hallway", "corridor", "passage", "staircase", "stairs", "steps", "elevator",
    "basement", "cellar", "attic", "loft",
    "balcony", "terrace", "patio", "deck", "porch", "foyer", "lobby",
    "ceiling", "floor", "hardwood floor", "tile floor", "carpet", "rug",
    "wallpaper", "painted wall", "white wall",
    "lamp", "chandelier", "candle", "fireplace", "fire",
    "bed", "sofa", "couch", "chair", "armchair", "bench", "table", "desk",
    "counter", "cabinet", "bookcase", "shelf", "shelves",
    "dresser", "nightstand", "wardrobe", "closet",
    "curtain", "curtains", "drapes", "blinds",
    "door", "wooden door", "glass door", "window", "window pane", "windowsill",
    "plant", "potted plant", "flower pot", "vase",
    "appliance", "refrigerator", "stove", "oven", "microwave",
    "television", "tv", "screen", "monitor", "computer", "laptop",
    "clock", "wall clock",
    "backstage", "stage", "locker room", "green room", "waiting room",
    "dungeon", "prison", "jail cell", "tomb", "crypt",
    "spaceship", "spacecraft", "futuristic interior", "sci-fi interior",
    "cockpit", "command center", "void", "abstract space", "surreal landscape",
];

// --------------- Looks / Appearance ------------------------------------------

export const LOOKS_KEYWORDS = [
    // Hair
    "hair", "very long hair", "long hair", "short hair", "medium hair", "half up half down", "thick hair",
    "straight hair", "wavy hair", "curly hair", "flowing hair", "hair over shoulder", "hair over one eye",
    "hair pull", "hair tie", "hair ornament", "hair clip", "hair between eyes",
    "bangs", "arched bangs", "blunt bangs", "side bangs", "swept bangs", "hime cut", "twintails",
    "twin braids", "pigtails", "double bun", "bun", "ponytail", "high ponytail", "low ponytail",
    "half up ponytail", "side ponytail", "braid", "braids", "french braid", "side braid", "long braids",
    "beehive", "ringlets", "spiral curls", "wavy", "waves", "permed", "bob cut", "pixie cut", "choppy",
    "layered", "mullet", "shag", "deathhawk", "spiked hair", "mohawk", "updo", "top knot", "fringe",
    "fringes", "side tail", "streaks", "hair streaks", "highlighted", "highlights", "colored hair",
    "green hair", "blue hair", "red hair", "pink hair", "white hair", "black hair", "brown hair",
    "orange hair", "purple hair", "yellow hair", "silver hair", "golden hair", "blonde", "gray hair",
    "grey hair", "dyed hair", "shiny hair", "glossy hair", "absurdly long hair",

    // Facial features
    "eyes", "green eyes", "blue eyes", "red eyes", "purple eyes", "yellow eyes", "brown eyes", "black eyes",
    "amber eyes", "hazel eyes", "grey eyes", "gray eyes", "heterochromia", "different colored eyes",
    "cross-eyed", "eyes closed", "eye contact", "half-closed eyes", "heavy-lidded", "sleepy eyes",
    "wide eyes", "large eyes", "small eyes", "slanted eyes", "sharp eyes", "gentle eyes", "sad eyes",
    "happy eyes", "angry eyes", "scared eyes", "evil eyes",
    "eyebrows", "thick eyebrows", "thin eyebrows", "connected eyebrows", "high eyebrows", "low eyebrows",
    "eyeshadow", "eyeliner", "eyelashes", "long eyelashes", "blush", "rosy cheeks", "cheek blush",
    "freckles", "mole", "beauty mark", "dimple", "smile", "smirk", "grin", "frown", "pout", "open mouth",
    "mouth", "lips", "red lips", "lipstick", "glossy lips", "full lips", "thin lips", "heart-shaped mouth",
    "tongue out", "fangs", "fang", "large fangs", "sharp teeth", "teeth", "buck teeth", "overbite",
    "expression", "blank expression", "cold expression", "gentle expression", "sad expression", "happy expression",
    "sweatdrop", "sweat drop",

    // Body features & build
    "body", "torso", "chest", "breasts", "small breasts", "medium breasts", "large breasts", "very large breasts",
    "perky breasts", "sagging breasts", "breast focus",
    "cleavage", "underboob", "sideboob", "abs", "six pack", "abdominal muscles", "muscular", "muscle definition",
    "toned", "fit", "athletic", "lean", "thin", "slim", "petite", "tiny", "skinny", "chubby", "curvy",
    "thick", "plump", "tall", "short", "stature", "hips", "wide hips", "thighs", "thick thighs", "thigh gap",
    "waist", "slim waist", "wide waist", "butt", "large butt", "flat butt", "legs", "long legs", "short legs",
    "calves", "ankles", "feet", "toes", "navel", "belly button", "midriff", "exposed midriff",
    "stomach", "skin", "pale skin", "fair skin", "light skin", "light-skinned", "dark skin", "dark-skinned", "back",
    "tanned", "tan skin", "brown skin", "white skin", "golden skin", "greenish skin", "blue skin", "grey skin",
    "tone", "light tone", "dark tone", "ash tone", "warm tone", "cool tone", "veined", "veins", "veiny",
    "armpit", "armpits", "armpit crease",

    // Accessories & adornments
    "accessory", "accesories", "jewelry", "earrings", "long earrings", "dangling earrings", "hoop earrings",
    "hat", "cap", "beanie", "beret", "crown", "tiara",
    "necklace", "pendant", "choker", "chain", "chain necklace", "beaded necklace", "gem necklace",
    "bracelet", "wrist cuff", "armband", "armlet", "gauntlet", "band", "cuff", "ring", "rings",
    "watch", "pocket watch", "headband", "hairband", "metal hairband", "bandeau", "headpiece", "diadem", "circlet",
    "halo", "angelic halo", "hair ornament", "hair clip", "hair stick", "hair comb", "hair fork",
    "flower", "flowers", "lace", "feather", "feathers", "ribbons", "ribbon", "bow", "bowtie",
    "bells", "bell", "beads", "beaded", "pearls", "gemstones", "gem",
    "studs", "spikes", "chains", "chain link",

    // Clothing - Upper body
    "shirt", "white shirt", "black shirt", "blouse", "top", "tank top", "tube top",
    "halter top", "sleeveless", "sleeveless shirt", "t-shirt", "long-sleeved", "long sleeves", "short sleeves",
    "puffy sleeves", "puffed sleeves", "bell sleeves", "flutter sleeves", "elbow length sleeves", "wrist cuffs",
    "shirt collar", "turtleneck", "high collar", "mock neck", "peter pan collar", "sailor collar",
    "chinese collar", "mandarin collar", "strapless", "backless", "cropped", "crop top", "fitted",
    "oversized", "loose", "baggy", "pleated", "ruched", "ruffled", "frilly", "frills", "ruffles",
    "lace", "lace trim", "lace sleeves", "cross-laced", "laced", "tied", "bow", "button-up", "buttons",
    "zipper", "zip-up", "front-zip", "back-zip", "cut-out", "cutout", "asymmetrical", "asymmetric",
    "transparent", "see-through", "sheer", "opaque", "patterned", "striped", "checkered", "plaid",
    "polka dot", "print", "solid", "leather", "silk", "satin", "cotton", "wool", "mesh",
    "jacket", "gakuran", "blazer", "cardigan", "sweater", "hoodie", "sweatshirt", "vest", "waistcoat",
    "coat", "coat tails", "trench coat", "overcoat", "denim jacket", "leather jacket", "bomber jacket",
    "cape", "cloak", "robe", "kimono", "half-open kimono", "yukata", "happi", "hanfu", "cheongsam",
    "qipao", "school uniform", "sailor uniform", "academy uniform", "military uniform",
    "combat uniform", "police uniform", "maid outfit", "maid uniform", "apron", "pinafore", "bib apron",
    "dress", "gown", "ball gown", "evening gown", "cocktail dress", "mini dress", "short dress",
    "knee-length dress", "long dress", "maxi dress", "asymmetrical dress",

    // Clothing - Lower body
    "skirt", "short skirt", "miniskirt", "mini skirt", "knee-length skirt", "long skirt", "maxi skirt",
    "puffed skirt", "layered skirt", "split skirt", "overskirt",
    "pleated skirt", "pleat skirt", "plaid skirt",
    "school skirt", "sailor skirt", "flared skirt", "a-line skirt", "tight skirt", "pencil skirt",
    "tulle skirt", "tutu", "frilly skirt", "ruffled skirt", "lace skirt",
    "mesh skirt", "see-through skirt", "sheer skirt", "translucent", "no panties", "pantyless",
    "pants", "trousers", "slacks", "dress pants", "leggings", "tights", "pantyhose", "stockings",
    "thigh highsocks", "thigh highs", "kneehighs", "knee highs", "ankle socks", "socks",
    "over-kneesocks", "zettai ryouiki", "absolute territory", "shorts", "short shorts",
    "hotpants", "boyshorts", "running shorts", "sweatpants", "joggers", "yoga pants",
    "gloves", "blue gloves", "white gloves", "black gloves", "thighhighs", "brown thighhighs",
    "capris", "capri pants", "cropped pants", "skinny jeans", "jeans", "denim", "cargo pants",
    "camo pants", "leather pants", "vinyl pants", "latex pants", "mesh pants",
    "bermuda shorts", "overall shorts", "romper", "jumpsuit", "onesie",

    // Footwear
    "shoes", "boots", "ankle boots", "knee boots", "knee-high boots", "over-the-knee boots", "thigh boots",
    "thigh-high boots", "combat boots", "platform boots", "cowboy boots", "go-go boots", "saddle shoes",
    "mary janes", "ballet flats", "oxfords", "loafers", "slip-ons", "sneakers", "athletic shoes",
    "converse", "canvas shoes", "high heels", "high-heeled boots", "heeled boots", "stilettos", "pumps",
    "wedges", "platform shoes", "platform heels", "strappy heels", "sandals", "flip-flops", "slippers",
    "barefoot", "bare feet", "tabi socks", "ninja tabi",

    // Legwear
    "stockings", "thigh stockings", "thigh-highs", "knee-high", "knee highs", "tube socks", "crew socks",
    "animal socks", "striped socks", "patterned socks", "lace stockings", "mesh stockings", "fishnets",
    "fishnet stockings", "pantyhose", "tights", "opaque tights", "patterned tights",
    "stocking seams", "torn stockings", "ripped stockings",

    // Head & Ear features
    "ears", "elf ears", "pointed ears", "long ears", "floppy ears", "cat ears", "fox ears", "dog ears", "tiger", "tiger ears",
    "animal ears", "animal ear fluff", "horns", "curved horns", "long horns", "spiral horns",

    // Other body modifications
    "tail", "tails", "fox tail", "cat tail", "dog tail", "wolf tail", "multiple tails", "fluffy tail",
    "wings", "angel wings", "demon wings", "fairy wings", "dragon wings", "big wings", "large wings",
    "small wings", "wings open", "feathers", "feathered wings", "bat wings",
    "tattoo", "tattoos", "sleeve tattoo",
    "scar", "scar on face", "scar over eye", "scar on cheek", "scar on arm", "bandages", "bandage",
    "bandaged", "eye patch", "monocle", "glasses", "eyeglasses", "spectacles", "round glasses",
    "cat eye glasses", "heart-shaped glasses", "sunglasses", "dark glasses", "goggles",
    "contacts", "contact lenses", "mask", "masquerade mask", "face mask", "medical mask",
    "piercing", "ear piercing", "nose piercing", "lip piercing", "tongue piercing", "navel piercing",
    "body piercing", "animal ear piercing", "chain piercing",

    // Makeup & beauty
    "makeup", "eyeliner", "winged eyeliner", "eyeshadow", "eye makeup", "lipstick", "lip gloss",
    "glossy lips", "red lipstick", "red lips", "matte lipstick", "foundation", "concealer", "blush",
    "rouge", "highlight", "contour", "mascara", "eyebrow pencil", "eyebrow makeup", "beauty mark",
    "mole", "beauty spot", "nail polish", "nails", "red nails", "nail art", "manicure", "pedicure",
    "nail color", "long nails", "short nails", "painted nails", "french tips",

    // Condition descriptors
    "wet", "wet hair", "wet clothes", "dripping", "dripping water", "dripping wet",
    "sweat", "sweating", "sweat drops", "sweat trail", "sweaty", "glistening", "shiny",
    "torn", "torn clothes", "ripped", "ripped clothes", "damaged", "battle damaged", "clothing damage",
    "covered", "covered in", "covered in mud", "dirty", "muddy", "stained", "blood stained",
    "scratchy", "rough", "weathered", "worn", "worn clothes", "tattered",
];

export const LOOKS_EXACT_TAGS = new Set([
    "v", "open mouth", "underwear", "cross-laced clothes", "cross-laced top",
    "condom", "animal ear fluff", "frills",
]);

// --------------- Action keywords ---------------------------------------------

export const ACTION_KEYWORDS = [
    "walking", "running", "sprinting", "jogging", "creeping", "crawling",
    "jumping", "leaping", "hopping", "bouncing", "flying", "floating", "hovering", "gliding",
    "falling", "tumbling", "rolling", "sliding", "spinning", "twirling", "dancing",
    "swaying", "shaking", "vibrating", "trembling", "shivering", "quivering",
    "swinging", "lunging", "charging", "rushing", "diving",
    "swimming", "wading", "surfing", "skateboarding", "roller skating", "ice skating", "cycling",
    "riding", "galloping", "trotting", "climbing", "scrambling", "scaling",
    "descending", "going down", "going up", "ascending", "sinking", "submerging", "emerging",
    "reaching", "reaching out", "reaching for", "touching", "grabbing", "holding", "grasping",
    "gripping", "clasping", "clutching", "clenching", "releasing", "dropping", "letting go",
    "throwing", "tossing", "hurling", "catching", "intercepting", "blocking", "parrying",
    "punch", "punching", "striking", "hitting", "slapping", "smacking", "swatting",
    "kicking", "kicking up", "stomping", "stepping",
    "pointing", "pointing at", "waving", "waving hand", "beckoning", "gesturing", "signaling",
    "placing hand", "placing hands", "resting hand", "hands on hips", "hands behind head",
    "hand on chest", "hands on face", "hands holding", "hands together", "hands clasped",
    "hands on another's shoulders", "hands on another's legs", "touching chest", "touching head",
    "arms crossed", "arms folded", "arms up", "arms raised", "arms outstretched", "arms extended",
    "arm around", "arm over", "arm between", "leg over", "leg between", "feet together", "feet apart",
    "standing on", "standing in", "sitting on", "sitting in", "lying on", "lying down", "kneeling",
    "crouching", "squatting", "bending", "bending forward", "bending over", "leaning", "leaning back",
    "leaning forward", "arching back", "stretching", "yawning", "sleeping", "napping", "resting",
    "fighting", "battle", "combat", "sparring", "dueling", "confronting", "attacking",
    "slashing", "smashing", "breaking", "destroying",
    "defeating", "evading", "retreating", "fleeing", "escaping",
    "aiming", "aiming at", "shooting", "shooting at", "firing", "casting", "casting spell",
    "summoning", "magic", "spell casting", "using magic", "enchantment",
    "smiling", "grinning", "laughing", "chuckling", "snickering", "giggling", "cackling",
    "crying", "weeping", "sobbing", "wailing", "whimpering", "shedding tears", "tears",
    "frowning", "pouting", "grimacing", "scowling", "glaring", "staring", "gazing", "looking",
    "glancing", "peeking", "peering", "observing", "watching",
    "yawning", "sighing", "gasping", "catching breath", "breathless",
    "surprised", "shocked", "amazed", "delighted", "pleased",
    "angry", "furious", "enraged", "annoyed", "irritated",
    "sad", "melancholy", "lonely", "depressed",
    "happy", "cheerful", "excited", "thrilled",
    "afraid", "scared", "frightened", "terrified", "panicked", "worried", "confused", "bewildered",
    "determined", "focused", "concentrating", "thinking", "pondering", "contemplating", "meditating",
    "standing", "standing still", "standing up", "sitting", "sitting down", "lying", "lying down",
    "on back", "on stomach", "on side", "on all fours", "on knees", "kneeling down", "crouching down",
    "bent over", "leaning back", "leaning forward", "leaning on", "supported by", "held by",
    "hugging", "hugging someone", "embracing", "cuddling", "snuggling", "spooning", "kissing",
    "kissing someone", "kissing hand", "licking", "nibbling", "biting", "sucking",
    "pinned", "bound", "tied", "restrained", "held down", "pushed", "pinned against",
    "on another's lap", "on another's shoulders", "on another's legs", "straddling", "mounted",
    "holding", "holding hands", "holding sword", "holding gun", "holding weapon", "wielding",
    "carrying", "carrying over shoulder", "carrying bridal style",
    "holding shield", "holding staff", "holding book", "reading", "holding pen", "writing",
    "holding drink", "drinking", "holding food", "eating", "holding cigarette", "smoking",
    "holding phone", "using phone", "holding camera", "taking photo",
    "picking up", "picking", "collecting", "gathering", "grabbing", "snatching", "stealing",
    "talking", "speaking", "chatting", "saying", "shouting", "yelling", "screaming", "shrieking",
    "calling", "calling out", "beckoning", "instructing", "ordering", "commanding", "requesting",
    "asking", "whispering", "muttering", "mumbling", "stuttering", "speaking softly",
    "speech bubble", "talking to", "listening", "hearing", "silent", "quiet",
    "playing sports", "playing soccer", "playing basketball", "exercising", "working out",
    "training", "practicing", "boxing", "wrestling", "yoga", "stretching",
];

// --------------- NSFW keywords -----------------------------------------------

export const NSFW_KEYWORDS = [
    "nsfw", "explicit", "uncensored", "censored",
    "nude", "naked", "full nude", "partial nude", "topless", "bottomless", "completely nude",
    "nipples", "nude nipples", "exposed nipples", "areola", "areolae", "areolas",
    "breast", "breasts", "boobs", "boobjob", "booby", "breast focus", "breast emphasis",
    "cleavage", "deep cleavage", "underboob", "underboob emphasis", "sideboob", "side boob",
    "pussy", "vagina", "vulva", "labia", "genital", "genitalia", "cunnilingus",
    "penis", "cock", "dick", "phallus", "erect", "erection", "hard", "bulge",
    "testicle", "testicles", "balls", "scrotum", "ballsack", "testes",
    "ass", "asshole", "anus", "anal", "butt", "butthole",
    "sex", "sexual", "fucking", "fuck", "sexual intercourse", "intercourse", "69", "groping", "handjob",
    "boobjob", "paizuri", "titty fuck", "tittyfuck",
    "penetration", "penetrating", "inserted", "insertion", "cock insertion",
    "cum", "cumshot", "ejaculation", "semen", "jizz", "spunk",
    "cum on face", "facial", "facial cumshot", "cum on cheek", "cum on breast", "cum on pussy",
    "cum on ass", "cum on body", "cumjob",
    "internal cumshot", "creampie", "cum inflation", "impregnation", "pregnancy",
    "bukkake", "multiple cumshot",
    "pregnancy", "pregnant", "pregnant belly",
    "lactation", "lactate", "milk", "suckling", "breast milk",
    "orgasm", "climax", "orgasmic", "cumming", "moaning", "pleasure",
    "arousal", "aroused", "lusty", "lecherous", "horny", "sexual desire", "sexual attraction",
    "blowjob", "blow job", "oral sex", "fellatio", "felatio", "sucking", "sucking penis", "sucking cock",
    "licking", "tongue", "mouth", "oral", "oral penetration",
    "french kiss", "deep kiss", "passionate kiss",
    "irrumatio", "facefucking", "face fucking", "deep throat",
    "anal", "anal sex", "anal intercourse", "anal penetration", "anal insertion",
    "bdsm", "bondage", "bound", "binding", "tied", "tied up", "restrained", "restraint",
    "rope", "rope bondage", "shibari", "kinbaku", "hogtied", "hog tied",
    "chains", "chained", "shackles", "handcuffs", "cuffs", "manacles", "fetters",
    "collar", "slave collar", "dog collar", "collar and leash",
    "leash", "leashed", "dominance", "submission", "submissive",
    "master", "master and slave", "dominant", "dom", "sub", "slave",
    "spanking", "whipping", "flogging", "paddle", "flogger", "caning", "beating",
    "humiliation", "humiliated", "public", "public sex", "public humiliation",
    "gagging", "gagged", "gag", "ball gag", "mouth gag", "silenced",
    "blindfold", "blindfolded", "sensory deprivation", "blindfold bondage",
    "fetish", "fetish content", "foot fetish", "feet", "foot worship", "footjob",
    "stockings", "pantyhose", "hosiery", "lingerie", "underwear", "panties", "bra",
    "thong", "transparent clothes", "see-through", "wet clothes", "clothing damage",
    "cumstain", "stained", "stain", "dirty", "soiled", "mess", "messy",
    "sweat", "sweating", "drool", "drooling", "saliva", "spit", "spitting",
    "tears", "crying", "crying tears", "painful", "pain", "hurting",
    "ahegao", "ahegao face", "cum face", "contorted face", "pleasure face", "ecstasy",
    "excessive cum", "cum pool", "cum puddle", "overfilled", "overflow",
    "tentacle", "tentacles", "tentacle sex", "tentacle penetration",
    "monster", "monster sex", "creature", "beast", "bestial", "zoophilia",
    "latex", "latex clothing", "rubber", "rubber suit", "catsuit", "bodysuit",
    "leather", "leather clothing", "leather outfit", "leather fetish",
    "high heels", "heeled", "platform heels", "stilettos", "heel fetish",
    "selfcest", "cloneji", "twin", "sibling", "siblings",
    "rape", "nonconsent", "non-consensual", "forced", "forcing", "unwilling",
    "drugged", "drugging", "incest", "father", "mother", "sibling", "family",
    "public sex", "public", "exhibitionism", "voyeurism", "voyeur", "peeping",
    "glory hole", "gloryhole",
    "necrophilia", "corpse", "dead body", "undead", "zombie sex",
    "piss", "urinating", "urination", "golden shower", "watersports", "precum", "pussy juice",
    "queef", "queefing", "squirt", "squirting", "female ejaculation",
    "blood", "bloody", "bleeding", "blood play",
    "no panties", "pantyless", "panty pull",
    "undressing", "undress", "stripping", "strip tease", "toplessness", "partial undress",
    "loose shirt", "slipping out", "slipping",
    "dress lift", "skirt lift", "lifted skirt", "raised skirt",
    "shorts pulled down", "pants down", "zipper open", "zipper", "unbuttoned", "unbuckled",
    "visible penis", "visible arousal", "shorts bulge", "pants bulge",
    "condom", "condom wrapper", "protection", "birth control", "safe sex",
    "bareback", "no condom", "raw", "creampie", "internal cumshot",
    "vibrator", "dildo", "sex toy", "sex toys",
    "hetero", "heterosexual", "straight", "straight couple",
    "homo", "homosexual", "homosexuality", "gay", "gay sex", "gay couple",
    "lesbian", "lesbian sex", "lesbian couple", "sapphic", "wlw",
    "yaoi", "boys love", "bl", "mlm",
    "bisexual", "bisexuality", "bi", "pansexual", "pansexuality",
    "interracial", "interspecies",
    "loli", "lolita", "underage", "minor", "child", "childlike body",
    "shotacon", "shota", "young boy", "underage boy", "childlike",
    "slutty", "slut", "whore", "prostitute",
    "degrading", "degradation", "embarrassing", "embarrassed",
    "public display", "displayed", "on display", "shame", "ashamed", "shamed",
    "ownership", "marked", "branded", "tattooed", "carved", "inscribed",
];

export const NSFW_EXACT_TAGS = new Set([
    "hetero", "bulge", "condom", "erection", "underwear", "open mouth",
]);

// --------------- Composition / Framing ----------------------------------------

export const COMPOSITION_META_KEYWORDS = [
    "looking at viewer", "looking at camera", "direct eye contact", "looking over shoulder", "from behind",
    "from below", "from above", "low angle", "high angle", "side view", "profile", "3/4 view",
    "camera view", "camera angle",
    "front view", "back view", "rear view", "top-down view", "pov", "first person", "first-person view",
    "dutch angle", "tilted", "dynamic angle", "foreshortening", "extreme foreshortening",
    "fisheye", "wide angle", "telephoto", "birds-eye view", "bird's eye view", "overhead shot",
    "aerial view", "drone view", "worm's eye view", "corner view", "edge of frame",
    "close-up", "close up", "extreme close-up", "face close-up", "head close-up", "portrait",
    "headshot", "head portrait", "bust shot", "upper body", "upper torso", "torso", "lower body",
    "full body", "full body shot", "full figure", "cowboy shot", "knee-up", "from waist up",
    "from waist down", "from knees down", "from chest up", "waist-up",
    "half-body", "half body", "quarter body", "three-quarter view", "side-by-side",
    "wide shot", "wide angle shot", "long shot", "establishing shot", "scenic shot", "landscape shot",
    "master shot", "two shot", "two-shot", "three shot", "group shot", "crowd shot",
    "centered", "centered on", "center of frame", "off-center", "off center", "left side", "right side",
    "left of frame", "right of frame", "top of frame", "bottom of frame", "edge of frame",
    "against wall", "by window", "at doorway", "on couch", "on bed", "on chair", "on table",
    "on ground", "on floor", "in corner", "in center", "on stage",
    "in foreground", "in background", "in midground", "mid ground",
    "depth of field", "bokeh", "sharp focus", "soft focus", "out of focus",
    "blurred background", "focus on", "focused on", "framed by", "frame within frame",
    "on another's lap", "on another's shoulders", "on another's legs", "on another's back",
    "straddling", "seated on", "sitting on", "standing on", "leaning against", "leaning on",
    "supported by", "held by", "carried by", "surrounded by", "enclosed by",
    "arms around", "arms over", "hand on", "hands on",
    "bloom", "sparkle", "sparkles", "sparkling", "glitter", "glittering", "shimmer", "shimmering",
    "glow", "glowing", "aura", "light effect", "light rays", "god rays", "lens flare", "flare",
    "halo", "halo effect", "glow effect", "bloom effect", "chromatic aberration",
    "vignette", "vignetting", "edge fade", "film grain", "grain", "scanlines",
    "reflection", "reflection in water", "reflection in mirror", "mirror", "window reflection",
    "shadow", "shadows", "cast shadow", "self shadow",
    "particle effect", "particles", "dust", "dust particles", "flower petals", "falling petals",
    "snow", "snowflakes", "rain", "rain drops", "water droplets", "water splash",
    "smoke", "smoke effect", "smoke clouds", "fog", "mist", "haze", "explosion", "explosion effect",
    "fire", "magical aura", "magical effect", "magical circle", "runic circle",
    "spell effect", "energy", "energy aura", "plasma", "lightning", "electricity", "storm",
    "heart", "hearts", "floating hearts", "heart shapes", "love", "love heart",
    "star", "stars", "starlight", "starry", "moon", "moon light", "moonlight", "moonlit",
    "sun", "sunlight", "sunlit", "sunrise", "sunset",
    "decorations", "banners", "flags", "bunting", "streamers", "confetti",
    "ribbons", "bows", "flowers", "floral", "ivy", "vines", "plants", "foliage",
    "ornaments", "ornamental", "decorative", "elaborate", "fancy", "intricate", "detailed",
    "looking at another", "looking at person", "looking away", "eyes closed",
    "silhouette", "silhouette shot",
    "symmetry", "symmetrical", "asymmetry", "asymmetrical", "balanced", "unbalanced",
    "rule of thirds", "golden ratio", "leading lines", "diagonal", "horizontal", "vertical",
    "triangular composition", "circular composition", "spiral composition",
    "empty space", "negative space", "positive space", "crowded", "sparse",
    "scenic", "scenery", "environment", "setting", "background", "foreground",
    "still life", "nature study", "landscape", "seascape", "cityscape",
    "x-ray", "transparent", "see-through", "cutaway", "cross-section", "diagram",
    "split screen", "side by side", "comparison", "before after", "time lapse", "sequence",
    "montage", "collage", "layered", "overlay", "blend", "merge", "fusion",
];
